export const DIFFICULTY_LEVELS = {
	EASY: 'easy',
	MEDIUM: 'medium',
	HARD: 'hard',
};

export const DIFFICULTY_ORDER = [
	DIFFICULTY_LEVELS.EASY,
	DIFFICULTY_LEVELS.MEDIUM,
	DIFFICULTY_LEVELS.HARD,
];

export const DIFFICULTY_LABELS = {
	[DIFFICULTY_LEVELS.EASY]: 'Easy',
	[DIFFICULTY_LEVELS.MEDIUM]: 'Medium',
	[DIFFICULTY_LEVELS.HARD]: 'Hard',
};
